#!/usr/bin/env bash
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small_10m.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small_100h.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small_960h.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/libri960_big.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_big_10m.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_big_100h.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_big_960h.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_10m_new.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_100h_new.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec2_vox_960h_new.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_10m_pl.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_100h_pl.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_960h_pl.pt
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec2_vox_960h.pt